# Specify docker-compose version
version: "3.8"

services:
  database:
    # Build the image from this directory
    image: 'tryhorus/database:0.1.0'
    # Specify the host and container port binding
    ports:
      - "7002:5432"
    # Restart the container if it stops (excl. manually) tto avoid downtimes
    restart: always
    # Container name
    container_name: horus_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002"]
      interval: 3s
      timeout: 5s
      retries: 5
    # Volume location
    volumes:
      - db-data:/var/lib/postgresql/data

  connector:
    image: 'tryhorus/connector:0.1.0'
    container_name: connector
    ports:
      - "3002:3002"
    # Build database before connector
    depends_on:
      - database
    restart: always
    links:
      - database

# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname

  ui-frontend:
    #image: 'tryhorus/ui-frontend:0.1.0'
    image: 'tryhorus/ui-client:0.1.0'
    container_name: ui-frontend
    ports:
      - "3000:3000"

  ui-server:
    image: 'tryhorus/ui-server:0.1.0'
    container_name: ui-server
    ports:
      - "5001:5001"
    restart: always
    depends_on:
      - database
    links:
      - database

volumes:
  db-data: