# Specify docker-compose version
version: "3.8"

services:
  database:
    # Build the image from this directory
    image: 'tryhorus/horus_db:test'
    # Specify the host and container port binding
    ports:
      - "7002:5432"
    # Restart the container if it stops (excl. manually) tto avoid downtimes
    restart: always
    # Container name
    container_name: horus_db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7002"]
      interval: 3s
      timeout: 5s
      retries: 5
    # Volume location
    volumes:
      - db-data:/var/lib/postgresql/data

  connector:
    image: 'tryhorus/connector:test'
    container_name: connector
    ports:
      - "3002:3002"
    # Build database before connector
    depends_on:
      - database
    restart: on-failure
    links:
      - database

# docker tag local-image:tagname new-repo:tagname
# docker push new-repo:tagname

  ui-client:
    image: 'tryhorus/ui-client:test'
    container_name: ui-client
    restart: always
    ports:
      - "3000:3000"

  ui-server:
    image: 'tryhorus/ui-server:test'
    container_name: ui-server
    ports:
      - "5001:5001"
    restart: on-failure
    depends_on:
      - database
    links:
      - database
    environment:
      - NODE_ENV=production
      - POSTGRES_ADMIN=horus_admin
      - POSTGRES_PASSWORD=horus_admin
      - DB_CONTAINER_NAME=horus_db
      - DB_NAME=horus
      - DB_PORT=5432

volumes:
  db-data:
